fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#hwi_oauth_redirect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /oauth/connect
#
#hwi_oauth_login:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix:   /oauth/login

bytefusion_lunch_admin:
    resource: "@BytefusionLunchAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

bytefusion_lunch_default:
    resource: "@BytefusionLunchDefaultBundle/Controller/"
    type:     annotation
    prefix:   /